name = input("Enter Your Name: ")
color = input("Enter your Favorite Color: ")
age = int(input("Enter a Age: "))
celebrity = input("Enter Your Favorite Celebrity: ")
city = input("Enter your Current City: ")
country = input("Enter your Current Country: ")

print("\n------------------------------")
print("\nYour name: " + name)
print("\nYour Favorite Color: " + color)
print("\nYour age: " + str(age))
print("\nYour Favorite Celebrity: " + celebrity)
print("\nYour Current City: " + city)
print("\nYour Current Country: " + country)
print("\n------------------------------")